global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "compass-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8000"]
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6380"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]

# Alert rules can be added here
rule_files:
  # - "alert.rules"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
